# Generated by Django 3.2.3 on 2021-11-24 21:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('hair_length', models.IntegerField(validators=[django.core.validators.MinValueValidator(25)])),
                ('hair_condition', models.CharField(blank=True, choices=[('high', 'high'), ('middle', 'middle'), ('low', 'low')], max_length=50, null=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='donate/')),
                ('approved', models.BooleanField(default=False)),
                ('beststory', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donate',
            name='donate_member',
            field=models.ManyToManyField(related_name='donate_member', through='donation.member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donate',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
