# Generated by Django 3.2.9 on 2021-11-20 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='hair_length',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(25)]),
        ),
    ]
