# Generated by Django 3.2.9 on 2021-11-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donate_hair_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='hair_condition',
            field=models.CharField(blank=True, choices=[('high', 'high'), ('middle', 'middle'), ('low', 'low')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='donate/'),
        ),
    ]
