# Generated by Django 3.2.9 on 2021-11-25 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='code',
        ),
        migrations.RemoveField(
            model_name='result',
            name='link',
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='result',
            name='result_score',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
